update luci-zerotier script
彻底变成 zerotier 包的辅助脚本，与原包共存

diff --git a/root/etc/init.d/luci-zerotier b/root/etc/init.d/luci-zerotier
--- a/root/etc/init.d/luci-zerotier
+++ b/root/etc/init.d/luci-zerotier
@@ -2,113 +2,97 @@
 
 START=99
 
-USE_PROCD=1
+PROG=/etc/init.d/zerotier
 
-PROG=/usr/bin/zerotier-one
-CONFIG_PATH=/var/lib/zerotier-one
-
-service_triggers() {
-	procd_add_reload_trigger "zerotier"
-	procd_add_interface_trigger "interface.*.up" wan /etc/init.d/luci-zerotier restart
+get_config() {
+	config_get_bool enabled $1 enabled 0
+	config_get_bool nat $1 nat 0
 }
 
-section_enabled() {
-	config_get_bool enabled "$1" 'enabled' 0
-	[ $enabled -gt 0 ]
+log() {
+	echo "$@"
+	logger -t luci-zerotier "$@" # debug
 }
 
-start_instance() {
-	local cfg="$1"
-	local port secret config_path
-	local ARGS=""
+start() {
+	config_load zerotier
+	config_foreach get_config zerotier
 
-	if ! section_enabled "$cfg"; then
-		echo "disabled in config"
-		return 1
-	fi
-  
-  [ -d /etc/config/zero ] || mkdir -p /etc/config/zero
-  config_path=/etc/config/zero
-  
-	config_get_bool port $cfg 'port'
-	config_get secret $cfg 'secret'
+	[ $enabled -eq 0 ] && log "Service disabled in config." && return 0
 
-	# Remove existing link or folder
-	rm -rf $CONFIG_PATH
+	# Ensure that the service is running
+	if ! $PROG running; then
+		log "Service status isn't running, and retry it ..."
+		# Try restart service once
+		$PROG restart
 
-	# Create link from CONFIG_PATH to config_path
-	if [ -n "$config_path" -a "$config_path" != $CONFIG_PATH ]; then
-		if [ ! -d "$config_path" ]; then
-			echo "ZeroTier config_path does not exist: $config_path"
-			return
+		# Wait service starting
+		sleep 1
+
+		# Maybe some other error in $PROG
+		if ! $PROG running; then
+			log "Service status isn't running, and retry failed!"
+			return 1
 		fi
-
-		ln -s $config_path $CONFIG_PATH
 	fi
 
-	mkdir -p $CONFIG_PATH/networks.d
+	[ $nat -eq 0 ] && log "NAT disabled in config." && return 0
 
-	if [ -n "$port" ]; then
-		ARGS="$ARGS -p$port"
-	fi
+	# Wait zt tun device
+	while [ "$(ifconfig | grep 'zt' | awk '{print $1}')" = "" ]
+	do
+		log "Waiting zt device ... "
+		sleep 1
+	done
 
-	if [ "$secret" = "generate" ]; then
-		echo "Generate secret - please wait..."
-		local sf="/tmp/zt.$cfg.secret"
+	local zt_devs FW
 
-		zerotier-idtool generate "$sf" > /dev/null
-		[ $? -ne 0 ] && return 1
-
-		secret="$(cat $sf)"
-		rm "$sf"
-
-		uci set zerotier.$cfg.secret="$secret"
-		uci commit zerotier
-	fi
-
-	if [ -n "$secret" ]; then
-		echo "$secret" > $CONFIG_PATH/identity.secret
-		# make sure there is not previous identity.public
-		rm -f $CONFIG_PATH/identity.public
-	fi
-
-	add_join() {
-		# an (empty) config file will cause ZT to join a network
-		touch $CONFIG_PATH/networks.d/$1.conf
-	}
-
-	config_list_foreach $cfg 'join' add_join
-
-	procd_open_instance
-	procd_set_param command $PROG $ARGS $CONFIG_PATH
-	procd_set_param stderr 1
-	procd_close_instance
+	zt_devs="$(ifconfig | grep 'zt' | awk '{print $1}')"
+	[ -x "$(command -v nft)" ] && FW="fw4" || FW="fw3"
+	for i in ${zt_devs}
+	do
+		if [ "$FW" = "fw3" ]; then
+			if iptables -S FORWARD | grep -sq "$i"; then
+				continue
+			fi
+			iptables -I FORWARD -i "$i" -j ACCEPT
+			iptables -I FORWARD -o "$i" -j ACCEPT
+			iptables -t nat -I POSTROUTING -o "$i" -j MASQUERADE
+		else
+			if nft list chain inet fw4 forward | grep -sq "$i"; then
+				continue
+			fi
+			nft insert rule inet fw4 forward iifname "$i" accept
+			nft insert rule inet fw4 forward oifname "$i" accept
+			nft insert rule inet fw4 srcnat oifname "$i" counter masquerade
+		fi
+		log "Added nat rules for zt interface $i!"
+	done
 }
 
-start_service() {
-	config_load 'zerotier'
-	config_foreach start_instance 'zerotier'
-	touch /tmp/zero.log && /etc/zerotier.start > /tmp/zero.log 2>&1 &
-}
+stop() {
+	local zt_devs FW
 
-stop_instance() {
-  rm -f /tmp/zero.log
-	local cfg="$1"
+	zt_devs="$(ifconfig | grep 'zt' | awk '{print $1}')"
+	[ -z "${zt_devs}" ] && return 0
 
-	/etc/zerotier.stop > /tmp/zero.log 2>&1
-
-	# Remove existing link or folder
-	rm -f $CONFIG_PATH/networks.d/*.conf
-	rm -rf $CONFIG_PATH
-}
-
-stop_service() {
-	config_load 'zerotier'
-	config_foreach stop_instance 'zerotier'
-}
-
-reload_service() {
-	stop
-	start
+	[ -x "$(command -v nft)" ] && FW="fw4" || FW="fw3"
+	for i in ${zt_devs}
+	do
+		if [ "$FW" = "fw3" ]; then
+			iptables -D FORWARD -i "$i" -j ACCEPT 2>/dev/null
+			iptables -D FORWARD -o "$i" -j ACCEPT 2>/dev/null
+			iptables -t nat -D POSTROUTING -o "$i" -j MASQUERADE 2>/dev/null
+		else
+			chains="forward srcnat"
+			for c in $chains; do
+				handles=$(nft -a list chain inet fw4 $c | grep -E "$i" | cut -d'#' -f2 | cut -d' ' -f3)
+				for h in $handles; do
+					nft delete rule inet fw4 $c handle $h
+				done
+			done
+		fi
+		log "Removed nat rules for zt interface $i!"
+	done
 }
 
